### ISSUE TITLE
Issue 5

### ISSUE THREAD

**Issue by lorenzorota** [iRath96/splix-bot#4] opened 2017-02-19 11:39 UTC
[![IMAGE ALT TEXT](http://img.youtube.com/vi/RbvsCdpcVUo/0.jpg)](http://www.youtube.com/watch?v=RbvsCdpcVUo "Video Title")

**Comment by iRath96** [comment] 2017-02-19 11:46
This is a duplicate of issue #1.

**Closed as completed by iRath96** 2017-02-19 11:46 UTC
Labels: duplicate
