### ISSUE TITLE
Issue 9

### ISSUE THREAD

**Issue by lorenzorota** [iRath96/splix-bot#8] opened 2017-02-19 11:41 UTC
[![IMAGE ALT TEXT](http://img.youtube.com/vi/_w6lp9hnh3s/0.jpg)](http://www.youtube.com/watch?v=_w6lp9hnh3s "Video Title")

**Comment by iRath96** [comment] 2017-02-19 11:55
This is a duplicate of #6.

**Closed as completed by iRath96** 2017-02-19 11:55 UTC
Labels: duplicate
