### ISSUE TITLE
Issue 4

### ISSUE THREAD

**Issue by lorenzorota** [iRath96/splix-bot#3] opened 2017-02-19 11:38 UTC
[![IMAGE ALT TEXT](http://img.youtube.com/vi/0l_rP340hbU/0.jpg)](http://www.youtube.com/watch?v=0l_rP340hbU "Video Title")

**Comment by iRath96** [comment] 2017-02-19 11:45
This is a duplicate of issue #1.

**Closed as completed by iRath96** 2017-02-19 11:45 UTC
Labels: duplicate
