### ISSUE TITLE
Issue 6

### ISSUE THREAD

**Issue by lorenzorota** [iRath96/splix-bot#5] opened 2017-02-19 11:40 UTC
[![IMAGE ALT TEXT](http://img.youtube.com/vi/KzbptUeMo3I/0.jpg)](http://www.youtube.com/watch?v=KzbptUeMo3I "Video Title")

**Comment by iRath96** [comment] 2017-02-19 11:46
This is a duplicate of issue #1.

**Closed as completed by iRath96** 2017-02-19 11:46 UTC
Labels: duplicate
